### ISSUE TITLE
Computer_optimized_layout_for_German_and_English

### ISSUE THREAD

**Issue by Virtual-Java** [mkrnr/plover_regenpfeifer#3]
Dear Martin,
today I've seen how to learn steno, after I found the openSource Steno software plover a view weeks ago.
After I tested multiple keyboard layouts (qwertz, neo2, adnw, koy) a view years ago (2020) I finally decided to learn KOY for everyday use.
Although I used to be able to type with over 250 keystrokes per minute, this was still a bit to slow to write down everything a human is talking.
That's why I want to learn typing steno on the computer and writing steno by hand.

Hopefully I can reach one day 250 words per minute and not just 250 strokes per minute!!!

Unfortunately i found neither an German variant of steno (official plover release) nor a program for learning the English plover. Can you recommend me such a (free and opensource) software?

A view years ago I co-worked on a project called Neo-/[KeyboardLayoutViewer](https://github.com/Virtual-Java/KeyboardLayoutViewer) and extended the number of displayable layouts from Neo only by ADNW, KOY, NEOQWERTY/Z.

This KeyboardLayoutViewer was very useful for me to learn in combination with Tipp10. After two weeks of training half an hour per day I was faster in writing KOY than searching the keys manually like an Eagle, so I could integrate the new keyboard layout into my daily work.

I have some plans to integrate a German or a English steno layout into this LayoutViewer, but therefore I have to know the German Layout.
The different layouts you described on your [webpage](https://stenoblog.com/working-on-a-german-steno-theory) resulted in another question:
Do you think it is possible to create a combined steno layout for German and English, that has been optimized with an modified version the [optimizer](http://509.ch/opt.7z) that was used for optimizing [ADNW and KOY](http://www.adnw.de/index.php?n=Main.SeitlicheNachbaranschl%c3%a4ge)?

This optimizer uses a dictionary with common combinations of letters and syllables (e.g. ei, en, er, ...). There are already two dictionaries, one for english and one for german.
I have already tested the optimizer – and it works. Only some features I am still missing.

I am interested in working together with you when optimizing plover/regenpfeifer is our goal.

**Comment by mkrnr** [comment]
Hi, sorry for the late response. I somehow didn't get notified.

You can have a look at https://stenoblog.com/working-on-a-german-steno-theory/ and https://stenoblog.com/regenpfeifer-layout-update/ for some context. In the second article I actually go over unifying the German and English layout. I still have separate dictionaries, however, because otherwise there would be way to many collisions or awkward workarounds. So even though it's the same layout, I swich between a German and English mode. Hope this helps.
