### ISSUE TITLE
No such file or dictionary: `...\\site-packages\\plover_regenpfeifer\\dictionaries\\r`

### ISSUE THREAD

**Issue by mkrnr** [mkrnr/plover_regenpfeifer#4]
The dictionary name is split into its individual letters.

Assumption: this in `system.py` should be a list instead of a tuple:
```
DEFAULT_DICTIONARIES = ('regenpfeifer_main.json')
```

**Comment by jast** [comment]
`('foo')` is actually identical to `'foo'`. If you want to force it into a tuple, it needs to be `('foo',)`.

**Comment by mkrnr** [comment]
Thanks a lot @jast, your suggestion was the way to go. First I wanted to make a list out of it but this needs to be a tuple.

The fix is part of v1.1.1 (and I had to create v1.1.2 because I burned v1.1.1 for some tests a while ago).
